// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Ybwg_gcnzcNGZmf9BSR5Z0H5LDLKWQU',
    appId: '1:547533760776:web:c5da6e7a498ab1c5c5e4bd',
    messagingSenderId: '547533760776',
    projectId: 'absensi-pegawai-x7',
    authDomain: 'absensi-pegawai-x7.firebaseapp.com',
    storageBucket: 'absensi-pegawai-x7.firebasestorage.app',
    measurementId: 'G-1SE8DKKDTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXsrsH-EkoRuVOUpBTS--vK8u_YWBt-Y',
    appId: '1:547533760776:android:8c8695297bc6c99dc5e4bd',
    messagingSenderId: '547533760776',
    projectId: 'absensi-pegawai-x7',
    storageBucket: 'absensi-pegawai-x7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dSa93U6fHx33-uFp87QgwTNdQNQjgXM',
    appId: '1:547533760776:ios:8b77a5b0823b1b3cc5e4bd',
    messagingSenderId: '547533760776',
    projectId: 'absensi-pegawai-x7',
    storageBucket: 'absensi-pegawai-x7.firebasestorage.app',
    iosBundleId: 'com.example.xsevenPresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dSa93U6fHx33-uFp87QgwTNdQNQjgXM',
    appId: '1:547533760776:ios:8b77a5b0823b1b3cc5e4bd',
    messagingSenderId: '547533760776',
    projectId: 'absensi-pegawai-x7',
    storageBucket: 'absensi-pegawai-x7.firebasestorage.app',
    iosBundleId: 'com.example.xsevenPresensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Ybwg_gcnzcNGZmf9BSR5Z0H5LDLKWQU',
    appId: '1:547533760776:web:6c16fbd738b05d4bc5e4bd',
    messagingSenderId: '547533760776',
    projectId: 'absensi-pegawai-x7',
    authDomain: 'absensi-pegawai-x7.firebaseapp.com',
    storageBucket: 'absensi-pegawai-x7.firebasestorage.app',
    measurementId: 'G-N8M4RS1CV9',
  );
}
